version: "3"

services:
  neo4j:
    image: neo4j:3.5.17
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"

  api:
    build: .
    command: npm start
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/app/api/src
    depends_on:
      - neo4j
    environment:
      - PORT=${PORT}
      - NEO4J_PROTOCOL=${NEO4J_PROTOCOL}
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_PORT=${NEO4J_PORT}
      - NEO4J_ENCRYPTION=ENCRYPTION_OFF